<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');
$root = "http://" . $_SERVER['HTTP_HOST'];
$root .= str_replace(basename($_SERVER['SCRIPT_NAME']), "", $_SERVER['SCRIPT_NAME']);
$config['base_url']                = "$root";
$config['system_ap_admin_folder']  = 'admin/';
$config['index_page']              = "index.php";
$config['uri_protocol']            = "AUTO";
$config['url_suffix']              = "";
$config['language']                = "vni";
$config['charset']                 = "UTF-8";
$config['enable_hooks']            = TRUE;
$config['subclass_prefix']         = 'MY_';
$config['permitted_uri_chars']     = 'a-z 0-9~%\.\:_\-';
$config['enable_query_strings']    = FALSE;
$config['controller_trigger']      = 'c';
$config['function_trigger']        = 'm';
$config['directory_trigger']       = 'd';
$config['log_threshold']           = 0;
$config['log_path']                = '';
$config['log_date_format']         = 'Y-m-d H:i:s';
$config['cache_path']              = '';
$config['encryption_key']          = "YOUR KEY";
$config['sess_cookie_name']        = 'ci_session';
$config['sess_expiration']         = 5;
$config['sess_encrypt_cookie']     = FALSE;
$config['sess_use_database']       = FALSE;
$config['sess_table_name']         = 'ci_sessions';
$config['sess_match_ip']           = FALSE;
$config['sess_match_useragent']    = TRUE;
$config['sess_time_to_update']     = 300;
$config['cookie_prefix']           = "";
$config['cookie_domain']           = "";
$config['cookie_path']             = "/";
$config['global_xss_filtering']    = FALSE;
$config['compress_output']         = FALSE;
$config['time_reference']          = 'local';
$config['rewrite_short_tags']      = FALSE;
$config['proxy_ips']               = '';
$config['system_row_per_page']     = 10;
$config['system_row_per_page01']   = 5;
$config['system_row_per_page02']   = 5;
$config['system_total_detail_row'] = 7;
$config['system_ap_prefix']        = 'picoplaza';

